version: '3.8'

services:
  app:
      build:
        context: .
      container_name: fastapi_app
      ports:
        - "8000:8000"
      working_dir: /app
      depends_on:
        - db
      env_file:
        - .env
      command: ["sh", "-c", "alembic revision --autogenerate -m \"Initial migration\" && alembic upgrade head && uvicorn app.api.main:app --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    depends_on:
      - app
      - db
    env_file:
      - .env
    command: ["python", "bot/main.py"]

volumes:
  postgres_data:
