version: '3.8'

services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    depends_on:
      - app
      - db
    env_file:
      - .env

volumes:
  postgres_data:
